### ISSUE TITLE
Missing metadata from referenced non-F# assemblies 

### ISSUE THREAD

**Issue by Vidarls** [fsharp/FSharp.Compiler.Service#235]
Following up on tpetricek/FSharp.Formatting#217 I have some questions regarding getting info on methods (static and instance) from C# types.

The `FSharpEntity` type have the member `MembersFunctionsAndValues`, but this one only includes properties from C# types. No methods, static or instance are ever listed here.

I can't seem to find any other way I _should_ have used to get this info.

My question: Is this a _feature_, _bug_, or _user error_?

Also, on C# types and members, the `.XmlDocSig` is always an empty string.

**Comment by matthid** [comment]
This is now partly fixed with 0.0.82 (methods are now there), however I noticed that private members are still missing in `MembersFunctionsAndValues` (for non-F# assemblies?). See tpetricek/FSharp.Formatting#259. I'm not sure if this is a natural limitation (because the F# compiler doesn't need private members from a reference) or a bug.

**Comment by dsyme** [comment]
Yes, I do recall that some private members get filtered on import - for the reason you mention -  I think somewhere at the Abstract IL level, we'd need to search aroud to find where (if anywhere!)

**Comment by dsyme** [comment]
Fixed in FCS 1.4.0.6

**Comment by matthid** [comment]
I don't think this is fixed, we still have missing metadata (non-public stuff) and recently one FSF user reported https://github.com/tpetricek/FSharp.Formatting/issues/362
