### ISSUE TITLE
Extend API to indicate project file evaluation failures from ProjectCracker.GetProjectOptionsFromProjectFileLogged

### ISSUE THREAD

**Issue by duckmatt** [fsharp/FSharp.Compiler.Service#520]
Hi, thanks for the great work on the `ProjectCracker`, could we expose any failures of evaluating a project file through `ProjectCracker.GetProjectOptionsFromProjectFileLogged`? At the moment it seems we need to extract exceptions from the log: https://github.com/fsprojects/FSharpLint/commit/740f89cdfc88edc681a0e99266e997cf566acc92

**Comment by rneatherway** [comment]
Ah yes, this is a bit unfortunate. How would you prefer to expose it? I also intend to change the logging so that a level can be specified, with "Error" as the default, so that a simple message rather than a huge log file can be given to the user.

**Comment by duckmatt** [comment]
That error logging would be great, but I think it would be useful to have the stack trace in there still so it can be logged in case anything unexpected happened in the ProjectCracker, but preferably I'd only want to display the exception's message to the user. I'm thinking perhaps the current tuple that's returned could become a DU along the lines of ` | ProjectCracked of projectOptions:FSharpProjectOptions * log:Map<string, string> | ProjectCrackedFailure of failureReason:string * log:Map<string, string>`

**Comment by rneatherway** [comment]
> That error logging would be great, but I think it would be useful to have the stack trace in there still so it can be logged in case anything unexpected happened in the ProjectCracker

Yes, I'd like to have both.

>  I'm thinking perhaps the current tuple that's returned could become a DU ... 

I'd like to loop in @dsyme to confirm that he's OK with me changing this API again. I think it is worth it for both of these things.

By the way, if an exception is raised then I don't think you will be able to get any useful log output.

**Comment by rneatherway** [comment]
@dsyme do you think this is going to be OK to change the function type, or should I create a new function?

**Comment by dsyme** [comment]
@rneatherway I'm OK with you changing the API but just use SemVer - so bump to 3.0.0.0 if needed.  I know it seems crazy but we will soon get used to it when we are at 99.0.0.0.  At least if I've understood SemVer correctly

@forki - any comments on this versioning approach?

**Comment by rneatherway** [comment]
That's OK, it seems sensible. I don't want to cause hassle for the downstream consumers.

@dungpa @vasily-kirichenko @tpetricek @Krzysztof-Cieslak please let me know your thoughts, if any, on how the project cracking interface should look, and what information you need to get from it.

In the light of this issue, and my other thoughts, I currently intend to make two changes:

1. Change the return type of `GetProjectOptionsFromProjectFileLogged` so that it indicates whether an exception was raised or not, and possibly whether the 'build' failed (although usually useful references are returned even if the 'build' fails).
2. Change the logging so that rather than "all or nothing" it defaults to "Error" like the command-line MSBuild, to increase the chance of users seeing useful messages to report. An enumeration (not the MSBuild Logger one, so we don't take that dependency) or other method of specifying the log level will also be provided.

**Comment by dsyme** [comment]
@rneatherway Where are we with this one? Thanks!

**Comment by rneatherway** [comment]
Happy to do the work, but basically waiting for feedback from the above mentioned people. The last change turned out to make things harder for the VFPT team, so I don't want to make another breaking change without making sure it will satisfy existing consumers.

I also ideally need some support from a couple of windows users. The Linux and Mac installations are very uniform, but on Windows you can have all kinds of awkward combinations of F# and Msbuild (with or without Visual Studio) and I can't easily test them all.

**Comment by dsyme** [comment]
With the advent of the new .NET SDK 2.0 prject file format the use of the project cracker is gradually declining.  It's good for what it is and has served us well, but I'm closing out old project cracker bugs as won't fix.  We can reactivate if really urgent.
