### ISSUE TITLE
FCS.ProjectCracker on dotnet core - msbuild version

### ISSUE THREAD

**Issue by ncave** [fsharp/FSharp.Compiler.Service#582]
Here is an outstanding issue for the dotnet core implementation of FCS.ProjectCracker:

1) The FSharp.Compiler.Service.ProjectCracker depends on building the cracked project with MSBuild to get the references from it, but:
2) The latest MSBuild (installed per [this](https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild#unofficial-getting-net-core-msbuild-binaries-without-building-the-code)) does not seem to be able to build older .fsproj projects, or at least not out of the box when I tried it.

This will probably improve when the next release of VS 15, please share if there is a MSBuild version that works with older fsharp projects.

In the mean time, some progress can be made by taking in [#566](https://github.com/fsharp/FSharp.Compiler.Service/pull/566) so at least the result after cracking has the project options and files, even if it cannot build properly to get the references (perhaps not everybody needs the references).

It's entirely possible that due to limited information I'm missing the big picture on where msbuild xplat is going, if that's the case please ignore.

**Comment by 7sharp9** [comment]
Having no msbuild in the equation would be nice.   msbuild dependent project are a major pain, it doesn't have to be that way.

**Comment by enricosada** [comment]
@ncave We need to ask msbuild repo team, i's open now, can you open an issue there about older fsproj? 
also /cc @cartermp too because it's interesting for visualfsharp i think, so if we can get some help it's good for everyone.

I'll open one about build and package. We need a package usable by preview1 (or preview2, but is the the same rc2 netcore) 
Problem is, it's not a good idea to use dev feed. 
Lot of strange stuff there ( rc2 rc3 ), and doing `-*` for deps may give wrong version or not working with preview1 sdk. 
Really it'is a pain to stay bleeding edge in dev feed, let's avoid it if possible, lost too much time. But now there is a working released preview1 so i am happy to use it and avoid pain

**Comment by ncave** [comment]
Here is the link to the issue on the MSBuild repo: [#709](https://github.com/Microsoft/msbuild/issues/709)
Looks like it's not possible at the moment, but perhaps in VS 15.

**Comment by ncave** [comment]
Closing as no longer seems relevant.
