### ISSUE TITLE
PCL project build tests failing on mono:latest os:linux

### ISSUE THREAD

**Issue by ncave** [fsharp/FSharp.Compiler.Service#648]
```
mono --version
Mono JIT compiler version 4.6.1 (Stable 4.6.1.3/abb06f1 Wed Sep 28 13:54:26 UTC 2016)
```

This one works:
`FSharp.Compiler.Service/tests/projects/Sample_VS2015_FSharp_Library_net45`

This one (and some others) fails:
`FSharp.Compiler.Service/tests/projects/Sample_VS2015_FSharp_Portable78_Library`
with:
`FSC: error FS0073: internal error: BuildFrameworkTcImports: no resolution of 'FSharp.Core.dll'`

**Comment by dsyme** [comment]
See https://github.com/fsharp/FSharp.Compiler.Service/pull/646

These days we recommend using the FSharp.Core nuget package for PCL compilation, especially on Linux/OSX.

**Comment by ncave** [comment]
@dsyme Does that mean FSharp.Core.dll is no longer installed as part of referenceassemblies-pcl?

**Comment by dsyme** [comment]
@ncave I'm not entirely sure.  I've been discussing with @directhex.  There are differences between the layout you get from compiling github.com/fsharp/fsharp (which works correctly and installs the PCL libraries) and the one used in the "csharp" Travis profile which I presume uses the Xamarin package).  The "csharp" Travis profile doesn't seem to even have the C# PCL reference assemblies installed.

Perhaps @directhex can advis

**Comment by directhex** [comment]
Best to loop in @akoeplinger, Travis is his iirc

**Comment by akoeplinger** [comment]
The "csharp" Travis profile **does** have the reference assemblies installed. It just installs the `referenceassemblies-pcl` and `fsharp` package from the Xamarin repositories (or the Mono MDK .pkg on Mac). If there's something wrong with how F# is installed there then we should coordinate on the Xamarin side :)

**Comment by dsyme** [comment]
@akoeplinger My bad, sorry, where do they get installed?  I did a recursive ``ls`` under ``/usr/lib/mono`` and didn't spot where they are, see results here https://travis-ci.org/fsharp/FSharp.Compiler.Service/jobs/166991797#L1029

@directhex Can you point me to the code that does the layout of the Xamarin package?  Also, we need to move ``fsc.exe`` and friends to ``/usr/lib/mono/fsharp`` rather than ``/usr/lib/mono/4.5`` per recent emai discussions (following the layout that http://github.com/fsharp/fsharp now uses - it would be great if we could just use exactly the same layout as that generates, though I know there are issues with also redirecting to /usr/lib/cli)

**Comment by akoeplinger** [comment]
@dsyme they're in `/usr/lib/mono/xbuild-frameworks/.NETPortable`, you need to pass -a to ls since they start with a dot and are hidden by default.

**Comment by dsyme** [comment]
> you need to pass -a to ls since the folder starts with a dot and so is hidden by default.

@akoeplinger  :) I would never, ever, ever have thought of that :)

**Comment by dsyme** [comment]
These are fixed
