### ISSUE TITLE
Make FSharpAccessibilityRights for different scopes available

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsharp/FSharp.Compiler.Service#690]
Reference: https://github.com/fable-compiler/Fable/issues/696

Consider the following code:

```fsharp
module private Foo = 
    let add x y = x + y
    let private add2 x y = x + y

Foo.add 2 2
```

When inspecting the typed AST `IsPrivate` returns true for both `Foo.add` and `Foo.add2` methods. Apparently this behaviour affects to all members of a private module. Not sure if this is by design, but as can be seen in the sample above, `add` is public and can be accessed from outside the module, so `IsPrivate` shouldn't eval to true for this symbol.

This affects Fable compilation as private members are not exported and cannot be accessed from outside the module.

**Comment by dsyme** [comment]
@alfonsogarciacaro Tricky.  Perhaps using ``IsPrivate`` is just wrong.

``private`` on the module means "private to the enclosing namespace declaration group".  So ``add`` is visible from the perspective of that namespace declaration group, but ``add2`` is not.  Both are ``private`` from the perspective of any other file or namespace declaration group.  

The problem is that what is visible will depend on where the module is viewed from.   I presume it would be execution-wise sound to have ``add`` in the compiled JS representation of the module, since it's visible from somewhere, i.e. you only trim out the things like ``add2`` that are really, really private.

It might be best to add a way to get the ``FSharpAccessibilityRights`` for the immediately enclosing namespace declaration group of the module.  You could then ask ``IsAccessible`` on each symbol in the module w.r.t. those access rights.   This would return ``true`` for ``add`` and ``false`` for ``add2``.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the insights @dsyme! Yes, I had a quick look at the code and I realized I was wrong about the value returned by `IsPrivate`, I thought it basically said if the `private` keyword was being used or not.

JS modules are an addition of ES2015 and correspond to files, so I'm simulating nested modules using a closure (as it was always done for JS in the past). I guess we can just fix this by attaching all members to the closure `exports` object no matter whether they are public or not. That wouldn't be very problematic as the private/public difference in JS is mainly in the file boundary, but it'd be nice to have a proper way to handle it.

Being able to grab the `FSharpAccessibilityRights` of the enclosing entity in order to check `IsAccessible` looks the most correct way to handle this indeed, though I guess it needs to be implemented because I didn't find a way to achieve the `FSharpAccessibilityRights` in FCS source code. Would it be easier to just allow checking if the symbol has the `private` modifier? This may not be as precise, but will probably work for Fable.

**Comment by dsyme** [comment]
> ... I guess we can just fix this by attaching all members to the closure exports object no matter whether they are public or not. ...

That sounds reasonable in the interim. Would that aid with debugging etc?

**Comment by alfonsogarciacaro** [comment]
Ok, I already [implemented that solution](https://github.com/fable-compiler/Fable/blob/5e4328ecea15dccd6518328d884e6519d3dab253/src/fable/Fable.Compiler/FSharp2Fable.Util.fs#L157-L162) :+1: I guess it won't affect that much the runtime execution, as it only affects private members of private modules, and where privacy really matters in JS is at the file level. Actually for classes all fields are already public, as there's no way in JS to hide them.

I'll keep the issue open in the hope a better fix comes in the future, but please feel free to close it if you think it's better.

Thanks a lot for your help!

**Comment by dsyme** [comment]
@alfonsogarciacaro Great. I'll leave it open as a feature request about FSharpAccessibilityRights
