### ISSUE TITLE
IsResultObsolete in Microsoft.FSharp.Compiler.SourceCodeServices appears to be internal in released package

### ISSUE THREAD

**Issue by smoothdeveloper** [fsharp/FSharp.Compiler.Service#695]
I'm looking to update FCS and IsResultObsolete seems to be private in the released package:

![image](https://cloud.githubusercontent.com/assets/87944/22851581/e269768e-f026-11e6-8435-8eda086e7224.png)

![image](https://cloud.githubusercontent.com/assets/87944/22851583/ede8751e-f026-11e6-8df8-c2083d4fc0b5.png)

Although in the code it appears to be not internal but the .fsi doesn't expose it:

https://github.com/fsharp/FSharp.Compiler.Service/blob/12209eb36a85e5049d2b501403ffd7a9370c848a/src/fsharp/vs/service.fsi

Am I right that this is an unintended public API change?

**Comment by smoothdeveloper** [comment]
Note that in VFPT this is used only once, and I'm trying to pass a raw lambda instead, that value then doesn't seem to be used at any callsite.

**Comment by dsyme** [comment]
@smoothdeveloper This was (silently) deprecated in FCS 10.0.1 because it has been replaced either by the passing of a CancellationToken for all calling APIs, or by the use of the cancellation token propagated by the returned Async  computation 

Apologies for the silent deprecation, we should have added an Obsolete on this type and kept it public.

**Comment by dsyme** [comment]
I'll close this though I wouldn't be surprised if other people hit the same issue during migration.

**Comment by smoothdeveloper** [comment]
Thanks for the notice @dsyme.

Maybe it is worth, if others face the issue, to put simple migration direction (showing before / after code).

In case of VFPT the sole call which used that was to `ParseAndCheckFileInProject` https://github.com/fsharp/FSharp.Compiler.Service/blob/c28509d14367314ad7038f2b2c5effa237abb1b3/src/fsharp/vs/service.fsi#L520 although the doc mentions that value will be passed to `hasTextChangedSinceLastTypecheck` I don't see that argument defined for that method.

Is there something else that needs to be changed in `ParseAndCheckFileInProject` documentation or a missing parameter?

**Comment by dsyme** [comment]
@smoothdeveloper The migration would just be to switch the calling code to use the relevant cancellation token rather than relying on callbacks to IsResutObsolete.  However I think people have always just been ignoring this parameter or passing ``(fun _ -> false)``.  If you have trouble migrating please link to the issue here and let's take a look, thanks
