### ISSUE TITLE
Garbled path info in the warning about missing directory

### ISSUE THREAD

**Issue by nightroman** [fsharp/FSharp.Compiler.Service#698]
Here is the script that causes the issue

````fsharp
    #I "some\missing\folder"
    let x = 42
````

Some ways to see the issue:

(1) Open it in Visual Studio 2015 (F# Power Tools is installed). Hover the
mouse over the expected error or look at the error pane. Note that the tip or
warnings message look like:

    Warning     The search directory 'some\missing older' could not be found

(2) Open it in VSCode (Ionide-fsharp is installed). In the tips and the problem
pane the message looks like 'some\missingolder'. Copy/paste from the problem
pane gets this text with unexpected "♀" instead of expected "\F":

    message: 'The search directory 'some\missingolder' could not be found'

(3) In my application using FCS the formatted message looks like this (same
unexpected "♀" instead of expected "\F"):

    warning FS0211: The search directory 'some\missing♀older' could not be found

**Comment by matthid** [comment]
Not sure if this is a bug. In https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/strings `\` is defined as escape character and `\f` seems to be:

```
> "\f".[0];;
val it : char = '\012'
```

Which seems to be not documented and seems to generate different outputs depending on the used console. From http://www.asciitable.com/ it seems to be the character to start a new page.

I think you depend on undefined behavior here. You should use:

```
#I @"some\missing\folder"
let x = 42
```

or `\\` instead of `\`.

However I'd be interested in clarification as well. /cc @dsyme. Maybe this should be posted in visualfsharp as well (Question on using `\` on an undefined next character)? Or maybe documentation should be extended.

**Comment by matthid** [comment]
Just to add some context. C# (https://msdn.microsoft.com/en-us/library/aa691090(v=vs.71).aspx) defines it like this:

> A character that follows a backslash character (\) in a regular-string-literal-character must be one of the following characters: ', ", \, 0, a, b, f, n, r, t, u, U, x, v. Otherwise, a compile-time error occurs.

Table is here https://msdn.microsoft.com/en-us/library/aa691087(v=vs.71).aspx

Imho this is a better default to what F# seems to be doing currently.

**Comment by nightroman** [comment]
Thank you. It's my error, indeed. I define garbage, F# just shows it. I am closing this.

The reason of my silly error is that the script uses a missing path deliberately. With a real path, I would notice my error at once.
