### ISSUE TITLE
Using AssemblyContents API and compiling faster

### ISSUE THREAD

**Issue by Jand42** [fsharp/FSharp.Compiler.Service#704]
We were looking for a way to get an `FSharpCheckProjectResults` and also compile a project the quickest way. 

Currently `checker.Compile` re-does all the type checking, even if it can reuse cached referenced assemblies, it is slower than desired for extensible compiler scenarios.

I made a quick, dirty and naive experiment of getting data from inside an `FSharpCheckProjectResults` to start a compilation with. IL seems to be generated ok, but optdata/sigdata is wrong in the resulting dll, making any dependent project fail with a bunch of errors like `optimize warning FS3186: An error occurred while reading the F# metadata node`.

My experiment is at https://github.com/Jand42/FSharp.Compiler.Service/tree/compile-from-checked

Are there any plans or work in progress for an extensible compiler or Roslyn-analyzer-like feature that would bring Services API and the compiler together to avoid type-checking twice? Thanks.

**Comment by dsyme** [comment]
@Jand42 Your PR seems plausible - there's no reason that I know of why this shouldn't work in principle.  Did you set ``keepAssemblyContents=true``? I assume so. It's probably just one other setting is wrong.

(With care we could probably make optimization incremental too, though there's no rush on that I suppose.  IlxGen and IlWrite codegen would be harder since both assume writing into a set of shared mutable data structures)

**Comment by Jand42** [comment]
Thank you for the encouragement. I will experiment further when my time allows, and will submit a PR whenever I can build multiple projects with it (comfirming that optdata/sigdata is usable).

**Comment by dsyme** [comment]
@Jand42 Any progress on a PR for this?

**Comment by Krzysztof-Cieslak** [comment]
I guess I'll bump again. @Jand42 any progress with it? If no, I'll put it on my to-do list as I may need it pretty soon for some performance fixes on a couple of features I've been looking at.
